import Helper.SeedGenerator as sg

#TOTAL_TIMESTEPS / (MAX_STEPS * N_ENVS) must be an integer
TOTAL_TIMESTEPS = 12000
MAX_STEPS = 1000
N_ENVS = 4

RANDOM_MAX_STEPS = MAX_STEPS
SCHEDULE_MAX_STEPS = MAX_STEPS
GREEDY_MAX_STEPS = MAX_STEPS

SUMO_INIT_STEPS = 200

SEED = sg.SEED

REWARD_THRESHOLD = 500

PEEK_INTERVAL = 50
PEEK_LEARN_STEPS = 50