import Helper.SeedGenerator as sg

MAX_LEARN_STEPS = 1000

RANDOM_MAX_LEARN_STEPS = MAX_LEARN_STEPS
SCHEDULE_MAX_LEARN_STEPS = MAX_LEARN_STEPS
GREEDY_MAX_LEARN_STEPS = MAX_LEARN_STEPS

# These should be lower or equal to the MAX LEARN STEPS ()
A2C_MAX_LEARN_STEPS = MAX_LEARN_STEPS
PPO_MAX_LEARN_STEPS = MAX_LEARN_STEPS
TRPO_MAX_LEARN_STEPS = MAX_LEARN_STEPS


TOTAL_TIMESTEPS = 1000
A2C_TOTAL_TIMESTEPS = TOTAL_TIMESTEPS
PPO_TOTAL_TIMESTEPS = TOTAL_TIMESTEPS
TRPO_TOTAL_TIMESTEPS = TOTAL_TIMESTEPS


SUMO_INIT_STEPS = 200

SEED = sg.SEED

REWARD_THRESHOLD = 500
