version: '3.1'

services:
    mysql-development:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: p8-mobility
        ports:
            - "3308:3306"
