START TRANSACTION;

CREATE TABLE IF NOT EXISTS Users
(
    Id           VARCHAR(40)  NOT NULL,
    UserName     VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    PasswordSalt VARCHAR(255) NOT NULL,
    UpdatedAt    TIMESTAMP    NOT NULL,
    PRIMARY KEY (Id)
);

COMMIT;